### ISSUE TITLE
Query:- Inline Payment

### ISSUE THREAD

**Issue by bhargavmehta** [craigchristenson/magento2-2checkout#1]
Hello,

Does this extension provide inline checkout method?

https://www.2checkout.com/hosted-checkout

Thank you

**Comment by craigchristenson** [comment]
I am currently working on this feature on the develop branch if you would like to check it out.
[https://github.com/craigchristenson/magento2-2checkout/tree/develop](https://github.com/craigchristenson/magento2-2checkout/tree/develop)

Any feedback you can provide would be greatly appreciated.

**Comment by craigchristenson** [comment]
The inline checkout feature has been merged to master. Please let me know if I can help further with the module.
