### ISSUE TITLE
ERROR CODE:PE101

### ISSUE THREAD

**Issue by refaelgold** [craigchristenson/magento2-2checkout#3]
Hey , i try to install your extension on mageplayground.tk but i get this error

ERROR CODE:PE101

any idea what its mean? thanks, nir

**Comment by refaelgold** [comment]
??

**Comment by craigchristenson** [comment]
PE101 is generally caused by a missing or invalid 2checkout seller id
(account number). This should be setup in your magento payment method
configuration. If you can confirm that this is setup correctly please let
me know and ill be happy to help you troubleshoot further.
